{% set version = "1.10.0" %}

package:
  name: pyaudi
  version: {{ version }}

source:
  url: https://github.com/darioizzo/audi/archive/v{{ version }}.tar.gz
  sha256: bd74e6040b6de88d4cc2caaa5b621b0ca334e6e657f25e95a77010caf140ca09

build:
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make       # [unix]
    - clang      # [win]
    - ninja      # [win]

  host:
    - libabseil
    - pybind11
    - pybind11-abi
    - libboost-devel
    - python
    - setuptools
    - eigen <5
    - obake-devel
    - mppp
    - audi {{ version }}

  run:
    - python
    - {{ pin_compatible('numpy') }}
  run_constrained:


about:
  home: http://darioizzo.github.io/audi/
  license: GPL-2.0-only OR GPL-3.0-only OR LGPL-3.0-only
  license_file:
    - COPYING.gpl3
    - COPYING.lgpl3
  summary: 'Python exposition of the audi C++ library: Algebra of Taylor truncated polynomials and a few algorithms useful for its applications (e.g. Automated differentiation, Differential Intelligence, Taylor Models, etc.)'
  dev_url: https://github.com/darioizzo/audi

extra:
  recipe-maintainers:
    - darioizzo
